targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/data/**/*.dart
            - lib/presentation/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/data/**/*.dart
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true