name: flutter_github_search
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: 2.5.1
  riverpod_generator: 2.4.0
  riverpod_annotation: 2.3.5
  freezed: ^2.5.2
  dio: ^5.5.0
  cached_network_image: 3.3.1
  go_router: ^14.2.0
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.2
  url_launcher: ^6.3.0
  json_annotation: ^4.9.0
  flutter_cache_manager: ^3.3.2
  collection: 1.18.0
  logger: ^2.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
flutter:
  uses-material-design: true